name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install dependencies for linting
      - name: Install Linters
        run: npm install eslint
          # Add commands to install your specific linters (e.g., npm install eslint)

      # Run linting
      - name: Lint Code
        run: eslint .
          # Add commands to run your linter (e.g., eslint .)

      # Login to container registry (securely store credentials as secrets)
      - name: Login to Docker Hub
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      # Initialize Terraform (consider using a specific Terraform version action)
      - name: Initialize Terraform
        run: |
          terraform init

      # Build the Docker container using Terraform
      - name: Build Docker Container
        run: |
          terraform build

      # Push the container to the registry
      - name: Push Docker Image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/your_image_name:latest